import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  selectedMessageScreen: null,
  isThreadOpen: false,
  params: {},
  alert: {visible: false, data: {}},
  commentModalIndex: -1,
  bottomSheetVisible: false,
  messageOptionData: null,
};

const modalSlice = createSlice({
  name: 'navigation',
  initialState,
  reducers: {
    setSelectedMessageScreen: (state, action) => {
      // console.log('action.payload', JSON.stringify(action.payload, null, 1));
      state.selectedMessageScreen = action.payload;
    },
    setThreadOpen: (state, action) => {
      state.isThreadOpen = action.payload;
    },
    setParams: (state, action) => {
      state.params = action.payload;
    },
    setAlert: (state, action) => {
      state.alert = action.payload;
    },
    setCommentModalIndex: (state, action) => {
      state.commentModalIndex = action.payload;
    },
    setBottomSheetVisible: (state, action) => {
      state.bottomSheetVisible = action.payload;
    },
    setMessageOptionData: (state, action) => {
      state.messageOptionData = action.payload;
    },
  },
});

// Export actions generated by createSlice
export const {
  setMessageOptionData,
  setSelectedMessageScreen,
  setThreadOpen,
  setParams,
  setAlert,
  setCommentModalIndex,
  setBottomSheetVisible,
} = modalSlice.actions;

// Export the reducer
export default modalSlice.reducer;
