import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  notifications: [],
  notificationCount: {},
};

const notificationSlice = createSlice({
  name: 'notification',
  initialState,
  reducers: {
    setNotifications: (state, action) => {
      state.notifications = action.payload;
    },
    setNotificationCount: (state, action) => {
      state.notificationCount = action.payload;
    },
    newNotification: (state, action) => {
      state.notifications.unshift(action.payload);
    },
    updateNotification: (state, action) => {
      const index = state.notifications.findIndex(
        n => n?._id === action.payload?._id,
      );
      if (index !== -1) {
        state.notifications[index].opened = true;
      }
    },
  },
});

// Export actions generated by createSlice
export const {
  setNotifications,
  newNotification,
  updateNotification,
  setNotificationCount,
} = notificationSlice.actions;

// Export the reducer
export default notificationSlice.reducer;
